//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Price
    {
        public Package_Price()
        {
            this.Packages = new HashSet<Package>();
        }
    
        public string package_type { get; set; }
        public decimal package_price1 { get; set; }
    
        public virtual ICollection<Package> Packages { get; set; }
    }
}
