//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int package_id { get; set; }
        public int length { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public int weight { get; set; }
        public string type { get; set; }
        public int order_id { get; set; }
        public int dispatcher_id { get; set; }
    
        public virtual Dispatcher Dispatcher { get; set; }
        public virtual Order Order { get; set; }
        public virtual Package_Price Package_Price { get; set; }
    }
}
