//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public float amount { get; set; }
        public System.DateTime payment_date { get; set; }
        public string UTR { get; set; }
        public string STATUS { get; set; }
        public int order_id { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
